name: Deploy Laravel Application to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, bcmath, pdo, pdo_mysql, xml, ctype, json, tokenizer

      - name: Install Composer Dependencies
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install PNPM Dependencies
        run: pnpm install

      - name: Build PNPM Assets
        run: pnpm run build

      # Setup known_hosts file
      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # Deploy with rsync - MODIFIED OPTIONS
      - name: Deploy with rsync
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key
          chmod 600 deploy_key
          # Using -rlgoDz instead of -avz to skip timestamp preservation (-t)
          rsync -rlgoDz --delete -e "ssh -i deploy_key" ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/html/malvar-ems/ --exclude=".git" --exclude="node_modules" --exclude=".pnpm" --exclude="vendor" --exclude=".env"
          rm deploy_key

      # Clear all caches first (including Filament)
      - name: Clear all caches
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/malvar-ems
            php artisan cache:clear
            php artisan config:clear
            php artisan view:clear
            php artisan route:clear
            php artisan filament:optimize-clear

      # Run Laravel commands separately to capture any errors
      - name: Run migrations
        uses: appleboy/ssh-action@master
        continue-on-error: true
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/malvar-ems
            php artisan migrate --force

      - name: Run optimization
        uses: appleboy/ssh-action@master
        continue-on-error: true
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/malvar-ems
            php artisan optimize
